# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Disable the default submodule logic
git:
  submodules: false

# Ensure we get the latest version of the (Geometrize library) submodule
before_install:
  - git submodule update --init --recursive

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build the documentation
script:
  - pushd doxygen
  - doxygen doxygen_config
  - popd

# Deploy the generated documentation using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/
  github_token: $GITHUB_API_KEY
  on:
    branch: master

after_success:
  - git add geometrize
  - git commit -m "Travis build bot updating Geometrize library submodule"